//TYPES AS CONSTS TO AVOID TYPOS
export const SET_ERROR = 'SET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const REMOVE_LOADING = 'REMOVE_LOADING';
export const GET_GENRES = 'GET_GENRES';
export const GET_MOVIES = 'GET_MOVIES';
export const GET_MOVIE_DETAILS = 'GET_MOVIE_DETAILS';
export const GET_MOVIE_VIDEOS = 'GET_MOVIE_VIDEOS';
export const ADD_TO_WATCHLIST = 'ADD_TO_WATCHLIST';
export const REMOVE_FROM_WATCHLIST = 'REMOVE_FROM_WATCHLIST';
export const GET_PERSON_MOVIES = 'GET_PERSON_MOVIES';
